# Generated by Django 4.2.2 on 2023-08-10 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('admin_no', models.CharField(max_length=255)),
                ('campus_or_branch', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=255)),
                ('mode_of_study', models.CharField(choices=[('regular', 'Regular'), ('part_time', 'Part Time'), ('parallel', 'Parallel'), ('boarding', 'Boarding'), ('day', 'Day'), ('online', 'Online')], max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('year_of_completion', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=20)),
                ('name_polling_station', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('institution_postal_address', models.CharField(max_length=100)),
                ('institution_telephone_no', models.CharField(max_length=100)),
                ('ammount_requesting', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyBackaground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(choices=[('both_parents_dead', 'Both Parents Dead'), ('one_parent_dead', 'One Parent Dead'), ('both_parents_alive', 'Both Parents Alive'), ('single_parent', 'Single Parent'), ('others', 'Others')], max_length=30)),
                ('number_siblings', models.CharField(max_length=10)),
                ('family_income', models.CharField(max_length=10)),
                ('family_expense', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=250)),
                ('father_address', models.CharField(max_length=250)),
                ('father_mobile_no', models.CharField(max_length=250)),
                ('father_occupation', models.CharField(max_length=250)),
                ('father_type_of_employment', models.CharField(choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None')], max_length=30)),
                ('father_main_source_of_income', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_address', models.CharField(max_length=200)),
                ('mother_telephone_number', models.CharField(max_length=15)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_type_of_employment', models.CharField(choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None')], max_length=30)),
                ('mother_main_source_of_income', models.CharField(max_length=100)),
                ('guardian_full_name', models.CharField(max_length=100)),
                ('guardian_address', models.CharField(max_length=200)),
                ('guardian_telephone_number', models.CharField(max_length=15)),
                ('guardian_occupation', models.CharField(max_length=100)),
                ('guardian_type_of_employment', models.CharField(choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None')], max_length=30)),
                ('guardian_main_source_of_income', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('school_or_college_or_university', models.CharField(max_length=100)),
                ('level_of_study', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
