# Generated by Django 4.2.2 on 2023-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personaldetails_familybackaground'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='id_or_passport_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
