# Generated by Django 4.2.2 on 2023-08-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_personaldetails_id_or_passport_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familybackaground',
            name='level_of_study',
        ),
        migrations.RemoveField(
            model_name='familybackaground',
            name='name',
        ),
        migrations.RemoveField(
            model_name='familybackaground',
            name='school_or_college_or_university',
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sibling_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
