# Generated by Django 4.2.2 on 2023-08-15 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_familybackaground_level_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('prev_bursary', models.TextField(default='Not Received')),
                ('org_bursary', models.TextField(default='Not Received')),
                ('disability', models.TextField(default='No')),
                ('chronic_illness', models.TextField(default='No')),
                ('fam_disability', models.TextField(default='No')),
                ('fam_chronic_illness', models.TextField(default='No')),
                ('fund_secondary', models.TextField(null=True)),
                ('fund_college', models.TextField(null=True)),
                ('fund_uni', models.TextField(null=True)),
                ('other_fund_secondary', models.TextField(null=True)),
                ('other_fund_college', models.TextField(null=True)),
                ('other_fund_uni', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_performance', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=50)),
                ('sent_away', models.TextField()),
                ('no_of_weeks', models.CharField(max_length=50)),
                ('annual_fees', models.CharField(max_length=50)),
                ('last_sem_fees', models.CharField(max_length=50)),
                ('current_sem_fees', models.CharField(max_length=50)),
                ('next_sem_fees', models.CharField(max_length=50)),
                ('helb_loan', models.CharField(max_length=50, null=True)),
                ('ref_one_name', models.CharField(max_length=100)),
                ('ref_one_address', models.CharField(max_length=255)),
                ('ref_one_number', models.CharField(max_length=40)),
                ('ref_two_name', models.CharField(max_length=100)),
                ('ref_two_address', models.CharField(max_length=255)),
                ('ref_two_number', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
