# Generated by Django 4.2.2 on 2023-08-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_additionalinformation_academicperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='permanent_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='physical_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='sub_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
