# Generated by Django 4.2.2 on 2023-08-19 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_report_form', models.FileField(upload_to='documents/transcripts/')),
                ('parents_guardians_id_card', models.FileField(blank=True, null=True, upload_to='documents/id_cards/')),
                ('students_id_card', models.FileField(blank=True, null=True, upload_to='documents/students_id_cards/')),
                ('birth_certificate', models.FileField(upload_to='documents/birth_certificates/')),
                ('school_id_card', models.FileField(blank=True, null=True, upload_to='documents/school_id_cards/')),
                ('parents_death_certificate', models.FileField(blank=True, null=True, upload_to='documents/death_certificates/')),
                ('fees_structure', models.FileField(upload_to='documents/fees_structures/')),
                ('admission_letters', models.FileField(blank=True, null=True, upload_to='documents/admission_letters/')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='documents/verification/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
