# Generated by Django 4.2.2 on 2023-08-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_application_number_of_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_applicant',
            field=models.IntegerField(null=True),
        ),
    ]
