# Generated by Django 4.2.2 on 2023-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_uploadeddocuments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocuments',
            name='application_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Incomplete', 'Incomplete'), ('Funded', 'Funded'), ('Disbursed', 'Disbursed')], default='Submitted', max_length=50, null=True),
        ),
    ]
