# Generated by Django 4.2.2 on 2023-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_uploadeddocuments_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='funds_available_for_secondary_schools',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='funds_available_for_universities',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
