# Generated by Django 4.2.2 on 2023-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_application_funds_available_for_secondary_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocuments',
            name='awarded',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
