# Generated by Django 4.2.2 on 2023-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_uploadeddocuments_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocuments',
            name='funds_for',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Secondary', 'Secondary'), ('Higher_Education', 'Higher Education')], default='Undefined', max_length=50, null=True),
        ),
    ]
