# Generated by Django 4.2.2 on 2023-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_uploadeddocuments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_applicant',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
