# Generated by Django 4.2.2 on 2023-09-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_uploadeddocuments_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocuments',
            name='urgency',
        ),
    ]
