# Generated by Django 4.2.2 on 2023-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_uploadeddocuments_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocuments',
            name='fees_structure',
            field=models.FileField(null=True, upload_to='documents/fees_structures/'),
        ),
        migrations.AlterField(
            model_name='uploadeddocuments',
            name='transcript_report_form',
            field=models.FileField(null=True, upload_to='documents/transcripts/'),
        ),
    ]
