# Generated by Django 4.2.2 on 2023-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_uploadeddocuments_fees_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='generation_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='manager_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='name_of_the_chairperson',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='p_o_box',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='p_o_box_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
