# Generated by Django 4.2.2 on 2023-09-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_ownerdetails_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocuments',
            old_name='id_card',
            new_name='id_card_birth_certificate',
        ),
        migrations.RemoveField(
            model_name='uploadeddocuments',
            name='birth_certificate',
        ),
    ]
