# Generated by Django 4.2.2 on 2023-09-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_id_card_uploadeddocuments_id_card_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocuments',
            name='letter_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
